// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// euclidean_distance
NumericMatrix euclidean_distance(NumericMatrix A, NumericMatrix B);
RcppExport SEXP fastmetrics_euclidean_distance(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_distance(A, B));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_euclidean_distance
NumericMatrix pairwise_euclidean_distance(NumericMatrix A);
RcppExport SEXP fastmetrics_pairwise_euclidean_distance(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_euclidean_distance(A));
    return rcpp_result_gen;
END_RCPP
}
// minkowski_distance
NumericMatrix minkowski_distance(NumericMatrix A, NumericMatrix B, float p);
RcppExport SEXP fastmetrics_minkowski_distance(SEXP ASEXP, SEXP BSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< float >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(minkowski_distance(A, B, p));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_minkowski_distance
NumericMatrix pairwise_minkowski_distance(NumericMatrix A, float p);
RcppExport SEXP fastmetrics_pairwise_minkowski_distance(SEXP ASEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< float >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_minkowski_distance(A, p));
    return rcpp_result_gen;
END_RCPP
}
