# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclidean_distance <- function(A, B) {
    .Call('fastmetrics_euclidean_distance', PACKAGE = 'fastmetrics', A, B)
}

pairwise_euclidean_distance <- function(A) {
    .Call('fastmetrics_pairwise_euclidean_distance', PACKAGE = 'fastmetrics', A)
}

