# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

canberra_rdist <- function(A) {
    .Call('rdist_canberra_rdist', PACKAGE = 'rdist', A)
}

canberra_pdist <- function(A) {
    .Call('rdist_canberra_pdist', PACKAGE = 'rdist', A)
}

canberra_cdist <- function(A, B) {
    .Call('rdist_canberra_cdist', PACKAGE = 'rdist', A, B)
}

euclidean_rdist <- function(A) {
    .Call('rdist_euclidean_rdist', PACKAGE = 'rdist', A)
}

euclidean_pdist <- function(A) {
    .Call('rdist_euclidean_pdist', PACKAGE = 'rdist', A)
}

euclidean_cdist <- function(A, B) {
    .Call('rdist_euclidean_cdist', PACKAGE = 'rdist', A, B)
}

hamming_rdist <- function(A) {
    .Call('rdist_hamming_rdist', PACKAGE = 'rdist', A)
}

hamming_pdist <- function(A) {
    .Call('rdist_hamming_pdist', PACKAGE = 'rdist', A)
}

hamming_cdist <- function(A, B) {
    .Call('rdist_hamming_cdist', PACKAGE = 'rdist', A, B)
}

jaccard_rdist <- function(A) {
    .Call('rdist_jaccard_rdist', PACKAGE = 'rdist', A)
}

jaccard_pdist <- function(A) {
    .Call('rdist_jaccard_pdist', PACKAGE = 'rdist', A)
}

jaccard_cdist <- function(A, B) {
    .Call('rdist_jaccard_cdist', PACKAGE = 'rdist', A, B)
}

manhattan_rdist <- function(A) {
    .Call('rdist_manhattan_rdist', PACKAGE = 'rdist', A)
}

manhattan_pdist <- function(A) {
    .Call('rdist_manhattan_pdist', PACKAGE = 'rdist', A)
}

manhattan_cdist <- function(A, B) {
    .Call('rdist_manhattan_cdist', PACKAGE = 'rdist', A, B)
}

maximum_rdist <- function(A) {
    .Call('rdist_maximum_rdist', PACKAGE = 'rdist', A)
}

maximum_pdist <- function(A) {
    .Call('rdist_maximum_pdist', PACKAGE = 'rdist', A)
}

maximum_cdist <- function(A, B) {
    .Call('rdist_maximum_cdist', PACKAGE = 'rdist', A, B)
}

minkowski_rdist <- function(A, p) {
    .Call('rdist_minkowski_rdist', PACKAGE = 'rdist', A, p)
}

minkowski_pdist <- function(A, p) {
    .Call('rdist_minkowski_pdist', PACKAGE = 'rdist', A, p)
}

minkowski_cdist <- function(A, B, p) {
    .Call('rdist_minkowski_cdist', PACKAGE = 'rdist', A, B, p)
}

